### ISSUE TITLE
Question about dockerhub and rolling tag

### ISSUE THREAD

**Issue by mrhydejc** [openclarity/kubeclarity#12]
Hello, congrat for the work.
I have a question about analysis on "rolling" tags like latest (or postgres 9.6).
When using postgres:9.6 in my cluster, I actually use postgres:9.6.17 (bad pactrice).
When postgres:9.6.18 is released, and the tags is updated, do Kubei scan the old postgres:9.6.17 as it is in use in my cluster or do it refer to 9.6.18 as it is referred by postgres:9.6 on the public registry ?

**Comment by akpsgit** [comment]
@mrhydejc, Thanks a lot for bringing it to our attention. This is indeed not best practice to use "rolling" tags and in this case the scan result will be for the new image in the registry instead of the actual image that is running. What would be the expected result in this case, to give a result for the running image and notify the user that a different image exists in the registry?

**Comment by mrhydejc** [comment]
@akpsgit Notify the user that the image is outdated by comparing the sha256 digest sounds like a good idea. 
Perhaps another solution can be considered with https://github.com/optiopay/klar/issues/153
