### ISSUE TITLE
API Available?

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [openclarity/kubeclarity#18]
I'd like to retrieve kubei run statistics from an external tool. Is there an API available?

For example to retrieve the number of vulnerabilities for a particular severity?

How can I achieve this from an external tool?

**Comment by Dynatrace-Adam-Gardner** [comment]
Bump....

**Comment by zohard1** [comment]
Hi Adam,

The webapp uses the Orchestrator pkg (part of the kubei pod) which implements the following interface:
type VulnerabilitiesScanner interface {
   Start() error
   Scan(scanConfig *config.ScanConfig) error
   ScanProgress() types.ScanProgress
   Results() *types.ScanResults
   Clear()
   Stop()
}
The communication is only with the webapp that results in html pages that are created by calling orchestrator's Results() which is
type ImageScanResult struct {
   PodName         string
   PodNamespace    string
   ImageName       string
   ContainerName   string
   ImageHash       string
   PodUid          string
   Vulnerabilities []*clair.Vulnerability
   Success         bool
   ScanErrMsg      string
}
type ScanResults struct {
   ImageScanResults []*ImageScanResult
   Progress         ScanProgress
}
and applies only for the current/last scan.

We'll be happy to discuss with you more in order to include in our roadmap a relevant API.

**Comment by PaulieMac** [comment]
> I'd like to retrieve kubei run statistics from an external tool. Is there an API available?
> 
> For example to retrieve the number of vulnerabilities for a particular severity?
> 
> How can I achieve this from an external tool?

I second this,  my use case is to use from a CI/CD pipeline, so (with kubei stuff marked with **** ):

->build my stack
->deploy my stack into k8s
->**** trigger kubei via api somehow, with a 'query', i.e. ?k8namespace='build_579'&workload='myNewWorkload'
->**** collect kubei results, and fail or pass depending on...?

->mark build as red or green

**Comment by Dynatrace-Adam-Gardner** [comment]
Hi Paulie, that's exactly my usecase too. In fact, my intention is to write a service for [Keptn](https://github.com/keptn/keptn) then Keptn will do that evaluation for you (pass / warning / fail), based on metrics from Kubei (and other metrics providers).

**Comment by zohard1** [comment]
We welcome external contributions to this open source, and plan to invest time in the future to port the integration from our commercial offering, that already have a CI integration for the open source scanning.
Meanwhile, you may consider our commercial product ( https://www.portshift.io/demo-request/ ), if relevant.

**Comment by testbotgt** [comment]
Hi, I am getting 404 when I try to reach the api according to the swagger directive. Do I need to do anything other than the default installation in the Kubernetes environment?

**Comment by FrimIdan** [comment]
@testbotgt can you please open a new issue with more information on which API you are trying to run and how the components were deployed.

**Comment by akpsgit** [comment]
@testbotgt, after the installation you can just port-forward (`kubectl port-forward --namespace kubeclarity svc/kubeclarity-kubeclarity 9999:8080`) and try to connect to the API server (on 9999 in this example). The UI uses the same API, so if the UI is working for you, no reason this shouldn't work

**Comment by sambetts-cisco** [comment]
KubeClarity now has support for Promethus metrics which provides things like the number of vulnerabilities for a particular severity, the API has also been expanded with a number of filters which can be used if the metrics don't work for you. This issue is > 3 years so I'm closing it as stale, if required we can reopen it to continue the discussion.
