### ISSUE TITLE
UI/UX Enhancements: It is will be useful to show analyzer and scanners in Applications page

### ISSUE THREAD

**Issue by pkalapat** [openclarity/kubeclarity#333]
**Is your feature request related to a problem? Please describe.**
It will be good to see the contributing analyzers and scanners in the applications view as a high level information. Right now scanners and analyzers can be seen after a few clicks and drilling down, 

**Describe the solution you'd like**
The Application dashboard  view  looks busy and omits useful information info like SBOM Analyzers and Scanners. Perhaps the real-estate could be used to show the analyzer and scanner as high level data instead of the "id" which is a cryptic string and that string can be seen from the detailed view anyways upon clicking the application. So the ID and the label informaton are redundant here and can be traded to present more high level insights like which analyzers and scanners are involved in reporting the vulnerabilities in that application. Attaching a screenshot for reference
<img width="1716" alt="Screen Shot 2023-02-09 at 5 43 06 PM" src="https://user-images.githubusercontent.com/3701244/217980115-b84227cc-afa5-4205-95b3-cd4d76b4279a.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by akpsgit** [comment]
@pkalapat, thanks for the suggestion. I don't think that Applications in the right screen for it, as it's a logical grouping of resources and not what is actually being scanned. The application ID is important here because it is used as the key to export the scan result from the CLI to associate the resource to an application.
I think that the Application Resources screen will be more suitable for that.
