### ISSUE TITLE
Execute scanner jobs in kubeclarity's namespace rather than in originating pod's

### ISSUE THREAD

**Issue by giovannirco** [openclarity/kubeclarity#389]
**Is your feature request related to a problem? Please describe.**
Each scanner job will be created on originating pod namespace, fetching logs as an example makes it hard as I need to specify each namespace rather than just matching a label

**Describe the solution you'd like**
A toggle on helm values to specify which namespace to spawn jobs and a blank value to leave it as it is now for backwards compatibility

**Describe alternatives you've considered**
I was thinking about using kyverno policies to mutate the namespace where the scanners will run 

**Additional context**

I have cilium installed in my cluster and I need to create rules for each namespace to allow scanners to do its job
I was also playing around with IRSA to allow scanners to fetch ECR images in a more secure manner
For both tasks having the scanners jobs in kubeclarity namespace would make things much easier

**Comment by FrimIdan** [comment]
Hi @giovannirco thanks for opening the issue.
The idea behind running the scanner job on the pod namespace is to be able to support scanning images that required image pull secrets to fetch the image, since the secret is in the same namespace of the pod.
Having said that, we can add a support to set the default scanners jobs namespace in case image pull secrets are not used.
