### ISSUE TITLE
Support for trivy token in helm charts

### ISSUE THREAD

**Issue by chandrahaas02** [openclarity/kubeclarity#486]
So I have a trivy server already running in my cluster with it's token I am planning to add kubeclarity to my cluster for quick weekly scans and for it beautiful UI , but there seems to be no way to add trivy token to kubeclarity helm chart, to use it

**Comment by CrazyByDefault** [comment]
@Tehsmash we've typically seen such charts provide support for either the plaintext value in values.yaml, or to provide a pre-existing secret name to be referenced. 

Example: bitnami/mariadb chart (most bitnami charts work this way iirc)

Plaintext value accepted - https://github.com/bitnami/charts/blob/main/bitnami/mariadb/values.yaml#L120,
OR
Existing Secret Ref - https://github.com/bitnami/charts/blob/main/bitnami/mariadb/values.yaml#L142

Their documentation highlights the chart's strategy in case both are specified -  

![image](https://github.com/openclarity/kubeclarity/assets/22311967/f0a4a30c-977b-48c9-8267-45d3b41c8ff8)

**Comment by FrimIdan** [comment]
> Putting credentials/tokens into a config map doesn't seem like a great idea, we might need to consider switching to using a secret. @FrimIdan WDYT?

@Tehsmash I Agree with @CrazyByDefault we can add support for both plaintext value OR existing secret ref

**Comment by Tehsmash** [comment]
@FrimIdan if we allow use of an existingSecret instead of embedding the token in the scanner template then that secret needs to be available where ever the scanner job is going to run (potentially that means that means a copy of that secret in every namespace on the cluster).

I think ultimately we need to give the token/read the token from a secret in the control plane/backend, and then the backend create a secret along with the job in the target namespace, and mount that as an environment var in the scanner job. WDYT?

**Comment by FrimIdan** [comment]
TBH, I think this is the user responsibility to make sure that the secret exist in the needed namespaces.
The runtime scanners can be configured to run in a specific namespace [here](https://github.com/openclarity/kubeclarity/blob/main/charts/kubeclarity/templates/scanner-template-configmap.yaml#L20C36-L20C60).
I want to avoid having the control plane have cluster permissions to read/write secrets.

**Comment by Tehsmash** [comment]
If we're happy to leave it to the operator/user to add the secrets in all the namespaces then I think we should only support having an existing secret name provided because we can't in good conscience support putting plaintext token/password in a configmap/job environment variable as that will expose the token as a security risk. We can't really create an unknown number of secrets through helm.

We'll need to document which namespaces will require this secret (any namespace with an image pull secret), and this will put additional overhead on the operator/user to add a secret for namespaces they create post-kubeclarity install that meant that requirement.
