### ISSUE TITLE
unable to use OciRegistry source error for runtime scanning

### ISSUE THREAD

**Issue by steezix** [openclarity/kubeclarity#511]
#### What happened:
Hello, I get the following error when running a runtime scan on my cluster:
`Some of the elements were failed to be scanned.`
Detailed error: `Failed to scan image "quay.io/argoproj/argo-events:latest". Effected pods: controller-manager-75855677bb-kb5vd/argo-events, webhook-sensor-hbwpn-6db5d778f6-9pxkv/argo-events. Reasons: failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: unable to load image: unable to use OciRegistry source: failed to get image descriptor from registry: GET https://quay.io/v2/argoproj/argo-events/manifests/sha256:73ae41d6fa46341e0e38f2810ea5d636d9c1d8820a92547c3d30ea604413aada: MANIFEST_UNKNOWN: manifest unknown; map[].`

#### What you expected to happen:
The runtime scan should be able to scan images coming from OciRegistry

#### How to reproduce it (as minimally and precisely as possible):
- Launch a runtime scan for a cluster that has some applications using images from Oci registries and you'll get the error

#### Environment:
- Kubernetes version: 1.24
- KubeClarity version: v2.21.1
- KubeClarity Helm Chart version: v2.21.1

**Comment by FrimIdan** [comment]
Hi @steezix thanks for opening the issue.
In order to better understand the issue can you please provide us with more information of out to reproduce the issue, for example - how the `argo-events` pods were deployed.
From the logs, it seems that the manifest that supposed to be scanned does not exist in the oci registry, I've also tried to pull the image via the digest and it failed:
```
$ docker pull quay.io/argoproj/argo-events@sha256:73ae41d6fa46341e0e38f2810ea5d636d9c1d8820a92547c3d30ea604413aada


Error response from daemon: manifest for quay.io/argoproj/argo-events@sha256:73ae41d6fa46341e0e38f2810ea5d636d9c1d8820a92547c3d30ea604413aada not found: manifest unknown: manifest unknown
```

So, maybe you it's a result of using `latest`, you are running an old image that the manifest does not exits in the remote repo any more, you can try to restart the relevant pods to see if a new image is being pulled (with new digest) and re-run the scan.

**Comment by steezix** [comment]
Hello @FrimIdan and thank you for your answer,
The argo-events pods have been deployed using Kustomize and the manifests of the argo-event github repo: https://github.com/argoproj/argo-events/blob/master/manifests/cluster-install/kustomization.yaml

Indeed, I misunderstood the error and your analysis was right. I deleted the pod, it got recreated with a newer image and I didn't face the issue anymore when running a new scan.

Thanks again!
