### ISSUE TITLE
How and where to specify imagePullSecrets for scanner-curl job

### ISSUE THREAD

**Issue by malagant** [openclarity/kubeclarity#61]
I need to provide an ImagePullSecret to pull the images for Klar and dockle from an Artifactory remote repository.
Where can this be done? I browsed through the source code, but maybe my Go lang knowledge needs to be improved to get the point. ;)
Any advice would greatly be appreciated.

**Comment by FrimIdan** [comment]
Hi @malagant,

By default the scanners will use the default SA, you can follow the instruction [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account) to configure ImagePullSecrets to a service account .

You can also configure `SCANNER_SERVICE_ACCOUNT` env var on Kubei deployment. This will deploy the scanners with the provided SA (and not the default) and then you can set ImagePullSecrets to that service account.

Hope it answers your question.

**Comment by malagant** [comment]
Sorry for the late reply. You're right that worked like a charm.
I had not thought about having the InagePullSecret in every namespace.
Maybe we could add an example scenario to the docs.

**Comment by FrimIdan** [comment]
Sure, we would love to accept a PR for that example scenario.

**Comment by malagant** [comment]
I'll prepare a PR next week.

**Comment by sambetts-cisco** [comment]
KubeClarity now has two different ways to provide ImagePullSecrets for scan jobs:

a) if the target pod has ImagePullSecrets configured, those secrets will be mounted into a scanner job in the same namespace as the original pod, and the scanner will determine the correct secret to use for the container being scanned
b) well defined ImagePullSecrets can be created in the KubeClarity deployment namespace, and the KubeClarity backend will find and mount those credentials into the scanner job too.

Given that we have this support, and based on the age of this issue I'm going to close it. If this doesn't cover this use case then I'll be happy to see this reopened so that we can resolve it further.
